FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt /app/backend_reqs.txt
COPY worker/requirements.txt /app/worker_reqs.txt

RUN pip install --no-cache-dir -r /app/backend_reqs.txt \ && pip install --no-cache-dir -r /app/worker_reqs.txt

COPY backend/ /app/backend/
COPY worker/ /app/worker/


CMD ["uvicorn", "backend.main:app","0.0.0.0" ,"--port","8000"]